CREATE TABLE "ITEM" (
    ID   VARCHAR(36) PRIMARY KEY NOT NULL,
    UUID VARCHAR(36),
    NAME VARCHAR(36)
);

CREATE TABLE "ADDRESS" (
    ID VARCHAR(36) PRIMARY KEY
);

CREATE TABLE "CONTACT" (
    ID VARCHAR(36) PRIMARY KEY
);

CREATE TABLE "ITEM_ADDRESS" (
    ID         BIGINT IDENTITY PRIMARY KEY,
    ITEM_ID    VARCHAR(36) NOT NULL,
    ADDRESS_ID VARCHAR(36) NOT NULL
);

CREATE TABLE "ITEM_CONTACT" (
    ID         BIGINT IDENTITY PRIMARY KEY,
    ITEM_ID    VARCHAR(36) NOT NULL,
    CONTACT_ID VARCHAR(36) NOT NULL
);
